name: "Build legacy Nix package on Ubuntu"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Check out LFS objects
        run: |
          git lfs pull  
      - uses: cachix/install-nix-action@v12
      - name: Building package
        run: nix-build . -A defaultPackage.x86_64-linux
